"use client";
import Head from "next/head";
import Header from "@/components/DashboardCom/Header";
import Layout from "@/components/DashboardCom/layout";
import { QueryClientProvider, QueryClient } from "react-query";
import { store } from "@/redux/empRedux/store";
import { Provider } from "react-redux";
import EmpHome from "./EmpHome";

const queryClient = new QueryClient();

const MainHomePage = () => {
  return (
    <QueryClientProvider client={queryClient}>
      <Provider store={store}>
        <>
          <Head>
            <title>BSMS</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Layout>
            <main className="bg-gray-100 min-h-screen flex-grow">
              <div className="ml-7">
                <Header />
              </div>
              <div className="py-5 px-0 ml-1">
                <EmpHome />
              </div>
            </main>
          </Layout>
        </>
      </Provider>
    </QueryClientProvider>
  );
};
export default MainHomePage;
